class DistrictCodeList {
  const DistrictCodeList({this.districtName, this.districtCode});

  final String districtName;
  final String districtCode;
}
const List<DistrictCodeList> ANList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Nicobars",districtCode: "003"),
  const DistrictCodeList(districtName: "North and Middle Andaman",districtCode: "001"),
  const DistrictCodeList(districtName: "South Andaman",districtCode: "002"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),


];
const List<DistrictCodeList> APList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Foreign Evacuees",districtCode: "-1"),
  const DistrictCodeList(districtName: "Anantapur",districtCode: "009"),
  const DistrictCodeList(districtName: "Chittoor",districtCode: "010"),
  const DistrictCodeList(districtName: "East Godavari",districtCode: "011"),
  const DistrictCodeList(districtName: "Guntur",districtCode: "005"),
  const DistrictCodeList(districtName: "Krishna",districtCode: "004"),
  const DistrictCodeList(districtName: "Kurnool",districtCode: "007"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Prakasam",districtCode: "012"),
  const DistrictCodeList(districtName: "S.P.S. Nellore",districtCode: "013"),
  const DistrictCodeList(districtName: "Srikakulam",districtCode: "014"),
  const DistrictCodeList(districtName: "Visakhapatnam",districtCode: "008"),
  const DistrictCodeList(districtName: "Vizianagaram",districtCode: "015"),
  const DistrictCodeList(districtName: "West Godavari",districtCode: "016"),
  const DistrictCodeList(districtName: "Y.S.R. Kadapa",districtCode: "006"),
];

const List<DistrictCodeList> ARList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Anjaw",districtCode: "022"),
  const DistrictCodeList(districtName: "Capital Complex",districtCode: "017"),
  const DistrictCodeList(districtName: "Changlang",districtCode: "020 "),
  const DistrictCodeList(districtName: "East Kameng",districtCode: "023"),
  const DistrictCodeList(districtName: "East Siang",districtCode: "042"),
  const DistrictCodeList(districtName: "Kamle",districtCode: "024"),
  const DistrictCodeList(districtName: "Kra Daadi",districtCode: "027"),
  const DistrictCodeList(districtName: "Kurung Kumey",districtCode: "021"),
  const DistrictCodeList(districtName: "Lepa Rada",districtCode: "033"),
  const DistrictCodeList(districtName: "Lohit",districtCode: "029"),
  const DistrictCodeList(districtName: "Longding",districtCode: "040"),
  const DistrictCodeList(districtName: "Lower Dibang Valley",districtCode: "031"),
  const DistrictCodeList(districtName: "Lower Siang",districtCode: "018"),
  const DistrictCodeList(districtName: "Lower Subansiri",districtCode: "032"),
  const DistrictCodeList(districtName: "Namsai",districtCode: "036"),
  const DistrictCodeList(districtName: "Pakke Kessang",districtCode: "019"),
  const DistrictCodeList(districtName: "Papum Pare",districtCode: "039"),
  const DistrictCodeList(districtName: "Shi Yomi",districtCode: "035"),
  const DistrictCodeList(districtName: "Siang",districtCode: "037"),
  const DistrictCodeList(districtName: "Tawang",districtCode: "030"),
  const DistrictCodeList(districtName: "Tirap",districtCode: "026"),
  const DistrictCodeList(districtName: "Upper Dibang Valley",districtCode: "025"),
  const DistrictCodeList(districtName: "Upper Siang",districtCode: "034"),
  const DistrictCodeList(districtName: "Upper Subansiri",districtCode: "041"),
  const DistrictCodeList(districtName: "West Kameng",districtCode: "028"),
  const DistrictCodeList(districtName: "West Siang",districtCode: "038"),
];

const List<DistrictCodeList> ASList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Airport Quarantine",districtCode: "-1"),
  const DistrictCodeList(districtName: "Baksa",districtCode: "046"),
  const DistrictCodeList(districtName: "Barpeta",districtCode: "047"),
  const DistrictCodeList(districtName: "Biswanath",districtCode: "765"),
  const DistrictCodeList(districtName: "Bongaigaon",districtCode: "057"),
  const DistrictCodeList(districtName: "Cachar",districtCode: "066"),
  const DistrictCodeList(districtName: "Charaideo",districtCode: "766"),
  const DistrictCodeList(districtName: "Chirang",districtCode: "058"),
  const DistrictCodeList(districtName: "Darrang",districtCode: "048"),
  const DistrictCodeList(districtName: "Dhemaji",districtCode: "062"),
  const DistrictCodeList(districtName: "Dhubri",districtCode: "059"),
  const DistrictCodeList(districtName: "Dibrugarh",districtCode: "043"),
  const DistrictCodeList(districtName: "Dima Hasao",districtCode: "067"),
  const DistrictCodeList(districtName: "Goalpara",districtCode: "060"),
  const DistrictCodeList(districtName: "Golaghat",districtCode: "053"),
  const DistrictCodeList(districtName: "Hailakandi",districtCode: "068"),
  const DistrictCodeList(districtName: "Hojai",districtCode: "764"),
  const DistrictCodeList(districtName: "Jorhat",districtCode: "054"),
  const DistrictCodeList(districtName: "Kamrup",districtCode: "050"),
  const DistrictCodeList(districtName: "Kamrup Metropolitan",districtCode: "049"),
  const DistrictCodeList(districtName: "Karbi Anglong",districtCode: "051"),
  const DistrictCodeList(districtName: "Karimganj",districtCode: "069"),
  const DistrictCodeList(districtName: "Kokrajhar",districtCode: "061"),
  const DistrictCodeList(districtName: "Lakhimpur",districtCode: "063"),
  const DistrictCodeList(districtName: "Majuli",districtCode: "767"),
  const DistrictCodeList(districtName: "Morigaon",districtCode: "055"),
  const DistrictCodeList(districtName: "Nagaon",districtCode: "056"),
  const DistrictCodeList(districtName: "Nalbari",districtCode: "052"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Sivasagar",districtCode: "044"),
  const DistrictCodeList(districtName: "Sonitpur",districtCode: "064"),
  const DistrictCodeList(districtName: "South Salmara Mankachar",districtCode: "768"),
  const DistrictCodeList(districtName: "Tinsukia",districtCode: "045"),
  const DistrictCodeList(districtName: "Udalguri",districtCode: "065"),
  const DistrictCodeList(districtName: "West Karbi Anglong",districtCode: "769"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];
const List<DistrictCodeList> BRList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Araria",districtCode: "074"),
  const DistrictCodeList(districtName: "Arwal",districtCode: "078"),
  const DistrictCodeList(districtName: "Aurangabad",districtCode: "077"),
  const DistrictCodeList(districtName: "Banka",districtCode: "083"),
  const DistrictCodeList(districtName: "Begusarai",districtCode: "098"),
  const DistrictCodeList(districtName: "Bhagalpur",districtCode: "082"),
  const DistrictCodeList(districtName: "Bhojpur",districtCode: "099"),
  const DistrictCodeList(districtName: "Buxar",districtCode: "100"),
  const DistrictCodeList(districtName: "Darbhanga",districtCode: "094"),
  const DistrictCodeList(districtName: "East Champaran",districtCode: "105"),
  const DistrictCodeList(districtName: "Gaya",districtCode: "079"),
  const DistrictCodeList(districtName: "Gopalganj",districtCode: "104"),
  const DistrictCodeList(districtName: "Jamui",districtCode: "107"),
  const DistrictCodeList(districtName: "Jehanabad",districtCode: "091"),
  const DistrictCodeList(districtName: "Kaimur",districtCode: "080"),
  const DistrictCodeList(districtName: "Katihar",districtCode: "075"),
  const DistrictCodeList(districtName: "Khagaria",districtCode: "101"),
  const DistrictCodeList(districtName: "Kishanganj",districtCode: "076"),
  const DistrictCodeList(districtName: "Lakhisarai",districtCode: "084"),
  const DistrictCodeList(districtName: "Madhepura",districtCode: "070"),
  const DistrictCodeList(districtName: "Madhubani",districtCode: "095"),
  const DistrictCodeList(districtName: "Munger",districtCode: "085"),
  const DistrictCodeList(districtName: "Muzaffarpur",districtCode: "086"),
  const DistrictCodeList(districtName: "Nalanda",districtCode: "090"),
  const DistrictCodeList(districtName: "Nawada",districtCode: "092"),
  const DistrictCodeList(districtName: "Patna",districtCode: "097"),
  const DistrictCodeList(districtName: "Purnia",districtCode: "073"),
  const DistrictCodeList(districtName: "Rohtas",districtCode: "081"),
  const DistrictCodeList(districtName: "Saharsa",districtCode: "071"),
  const DistrictCodeList(districtName: "Samastipur",districtCode: "096"),
  const DistrictCodeList(districtName: "Saran",districtCode: "102"),
  const DistrictCodeList(districtName: "Sheikhpura",districtCode: "093"),
  const DistrictCodeList(districtName: "Sheohar",districtCode: "087"),
  const DistrictCodeList(districtName: "Sitamarhi",districtCode: "088"),
  const DistrictCodeList(districtName: "Siwan",districtCode: "103"),
  const DistrictCodeList(districtName: "Supaul",districtCode: "072"),
  const DistrictCodeList(districtName: "Vaishali",districtCode: "089"),
  const DistrictCodeList(districtName: "West Champaran",districtCode: "106"),
];
const List<DistrictCodeList> CHList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Chandigarh",districtCode: "108"),
];
const List<DistrictCodeList> CTList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Balod",districtCode: "110"),
  const DistrictCodeList(districtName: "Baloda Bazar",districtCode: "111"),
  const DistrictCodeList(districtName: "Balrampur",districtCode: "112"),
  const DistrictCodeList(districtName: "Bametara",districtCode: "114"),
  const DistrictCodeList(districtName: "Bastar",districtCode: "113"),
  const DistrictCodeList(districtName: "Bijapur",districtCode: "115"),
  const DistrictCodeList(districtName: "Bilaspur",districtCode: "116"),
  const DistrictCodeList(districtName: "Dakshin Bastar Dantewada",districtCode: "117"),
  const DistrictCodeList(districtName: "Dhamtari",districtCode: "118"),
  const DistrictCodeList(districtName: "Durg",districtCode: "119"),
  const DistrictCodeList(districtName: "Gariaband",districtCode: "120"),
  const DistrictCodeList(districtName: "Janjgir Champa",districtCode: "121"),
  const DistrictCodeList(districtName: "Jashpur",districtCode: "122"),
  const DistrictCodeList(districtName: "Kabeerdham",districtCode: "135"),
  const DistrictCodeList(districtName: "Kondagaon",districtCode: "124"),
  const DistrictCodeList(districtName: "Korba",districtCode: "124"),
  const DistrictCodeList(districtName: "Koriya",districtCode: "126"),
  const DistrictCodeList(districtName: "Mahasamund",districtCode: "127"),
  const DistrictCodeList(districtName: "Mungeli",districtCode: "128"),
  const DistrictCodeList(districtName: "Narayanpur",districtCode: "129"),
  const DistrictCodeList(districtName: "Raigarh",districtCode: "130"),
  const DistrictCodeList(districtName: "Raipur",districtCode: "109"),
  const DistrictCodeList(districtName: "Rajnandgaon",districtCode: "131"),
  const DistrictCodeList(districtName: "Sukma",districtCode: "132"),
  const DistrictCodeList(districtName: "Surajpur",districtCode: "133"),
  const DistrictCodeList(districtName: "Surguja",districtCode: "134"),
  const DistrictCodeList(districtName: "Uttar Bastar Kanker",districtCode: "123"),
  const DistrictCodeList(districtName: "Gaurela Pendra Marwahi",districtCode: "136"),

];
const List<DistrictCodeList> DLList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Central Delhi",districtCode: "141"),
  const DistrictCodeList(districtName: "East Delhi",districtCode: "145"),
  const DistrictCodeList(districtName: "New Delhi",districtCode: "140"),
  const DistrictCodeList(districtName: "North Delhi",districtCode: "146"),
  const DistrictCodeList(districtName: "North East Delhi",districtCode: "147"),
  const DistrictCodeList(districtName: "North West Delhi",districtCode: "143"),
  const DistrictCodeList(districtName: "Shahdara",districtCode: "148"),
  const DistrictCodeList(districtName: "South Delhi",districtCode: "149"),
  const DistrictCodeList(districtName: "South East Delhi",districtCode: "144"),
  const DistrictCodeList(districtName: "South West Delhi",districtCode: "150"),
  const DistrictCodeList(districtName: "West Delhi",districtCode: "142"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];

const List<DistrictCodeList> DNList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Dadra and Nagar Haveli",districtCode: "137"),
  const DistrictCodeList(districtName: "Daman",districtCode: "-1"),
  const DistrictCodeList(districtName: "Diu",districtCode: "-1"),
];
const List<DistrictCodeList> GAList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "North Goa",districtCode: "151"),
  const DistrictCodeList(districtName: "South Goa",districtCode: "152"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];

const List<DistrictCodeList> GJList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Ahmedabad",districtCode: "154"),
  const DistrictCodeList(districtName: "Amreli",districtCode: "174"),
  const DistrictCodeList(districtName: "Anand",districtCode: "179"),
  const DistrictCodeList(districtName: "Aravalli",districtCode: "158"),
  const DistrictCodeList(districtName: "Banaskantha",districtCode: "159"),
  const DistrictCodeList(districtName: "Bharuch",districtCode: "180"),
  const DistrictCodeList(districtName: "Bhavnagar",districtCode: "175"),
  const DistrictCodeList(districtName: "Botad",districtCode: "176"),
  const DistrictCodeList(districtName: "Chhota Udaipur",districtCode: "181"),
  const DistrictCodeList(districtName: "Dahod",districtCode: "182"),
  const DistrictCodeList(districtName: "Dang",districtCode: "163"),
  const DistrictCodeList(districtName: "Devbhumi Dwarka",districtCode: "168"),
  const DistrictCodeList(districtName: "Gandhinagar",districtCode: "153"),
  const DistrictCodeList(districtName: "Gir Somnath",districtCode: "177"),
  const DistrictCodeList(districtName: "Jamnagar",districtCode: "169"),
  const DistrictCodeList(districtName: "Junagadh",districtCode: "178"),
  const DistrictCodeList(districtName: "Kheda",districtCode: "156"),
  const DistrictCodeList(districtName: "Kutch",districtCode: "170"),
  const DistrictCodeList(districtName: "Mahisagar",districtCode: "183"),
  const DistrictCodeList(districtName: "Mehsana",districtCode: "160"),
  const DistrictCodeList(districtName: "Morbi",districtCode: "171"),
  const DistrictCodeList(districtName: "Narmada",districtCode: "184"),
  const DistrictCodeList(districtName: "Navsari",districtCode: "164"),
  const DistrictCodeList(districtName: "Panchmahal",districtCode: "185"),
  const DistrictCodeList(districtName: "Patan",districtCode: "161"),
  const DistrictCodeList(districtName: "Porbandar",districtCode: "172"),
  const DistrictCodeList(districtName: "Rajkot",districtCode: "173"),
  const DistrictCodeList(districtName: "Sabarkantha",districtCode: "162"),
  const DistrictCodeList(districtName: "Surat",districtCode: "165"),
  const DistrictCodeList(districtName: "Surendranagar",districtCode: "157"),
  const DistrictCodeList(districtName: "Tapi",districtCode: "166"),
  const DistrictCodeList(districtName: "Vadodara",districtCode: "155"),
  const DistrictCodeList(districtName: "Valsad",districtCode: "167"),
];
const List<DistrictCodeList> HPList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Bilaspur",districtCode: "219"),
  const DistrictCodeList(districtName: "Chamba",districtCode: "214"),
  const DistrictCodeList(districtName: "Hamirpur",districtCode: "217"),
  const DistrictCodeList(districtName: "Kangra",districtCode: "213"),
  const DistrictCodeList(districtName: "Kinnaur",districtCode: "216"),
  const DistrictCodeList(districtName: "Kullu",districtCode: "211"),
  const DistrictCodeList(districtName: "Lahaul and Spiti",districtCode: "210"),
  const DistrictCodeList(districtName: "Mandi",districtCode: "215"),
  const DistrictCodeList(districtName: "Shimla",districtCode: "208"),
  const DistrictCodeList(districtName: "Sirmaur",districtCode: "212"),
  const DistrictCodeList(districtName: "Solan",districtCode: "209"),
  const DistrictCodeList(districtName: "Una",districtCode: "218"),
];
const List<DistrictCodeList> HRList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Foreign Evacuees",districtCode: "-1"),
  const DistrictCodeList(districtName: "Ambala",districtCode: "193"),
  const DistrictCodeList(districtName: "Bhiwani",districtCode: "200"),
  const DistrictCodeList(districtName: "Charkhi Dadri",districtCode: "201"),
  const DistrictCodeList(districtName: "Faridabad",districtCode: "199"),
  const DistrictCodeList(districtName: "Fatehabad",districtCode: "196"),
  const DistrictCodeList(districtName: "Gurugram",districtCode: "188"),
  const DistrictCodeList(districtName: "Hisar",districtCode: "191"),
  const DistrictCodeList(districtName: "Italians",districtCode: "-1"),
  const DistrictCodeList(districtName: "Jhajjar",districtCode: "189"),
  const DistrictCodeList(districtName: "Jind",districtCode: "204"),
  const DistrictCodeList(districtName: "Kaithal",districtCode: "190"),
  const DistrictCodeList(districtName: "Karnal",districtCode: "203"),
  const DistrictCodeList(districtName: "Kurukshetra",districtCode: "186"),
  const DistrictCodeList(districtName: "Mahendragarh",districtCode: "206"),
  const DistrictCodeList(districtName: "Nuh",districtCode: "205"),
  const DistrictCodeList(districtName: "Palwal",districtCode: "207"),
  const DistrictCodeList(districtName: "Panchkula",districtCode: "187"),
  const DistrictCodeList(districtName: "Panipat",districtCode: "195"),
  const DistrictCodeList(districtName: "Rewari",districtCode: "202"),
  const DistrictCodeList(districtName: "Rohtak",districtCode: "192"),
  const DistrictCodeList(districtName: "Sirsa",districtCode: "194"),
  const DistrictCodeList(districtName: "Sonipat",districtCode: "198"),
  const DistrictCodeList(districtName: "Yamunanagar",districtCode: "197"),

];
const List<DistrictCodeList> JHList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Bokaro",districtCode: "242"),
  const DistrictCodeList(districtName: "Chatra",districtCode: "245"),
  const DistrictCodeList(districtName: "Deoghar",districtCode: "253"),
  const DistrictCodeList(districtName: "Dhanbad",districtCode: "257"),
  const DistrictCodeList(districtName: "Dumka",districtCode: "258"),
  const DistrictCodeList(districtName: "East Singhbhum",districtCode: "247"),
  const DistrictCodeList(districtName: "Garhwa",districtCode: "243"),
  const DistrictCodeList(districtName: "Giridih",districtCode: "256"),
  const DistrictCodeList(districtName: "Godda",districtCode: "262"),
  const DistrictCodeList(districtName: "Gumla",districtCode: "251"),
  const DistrictCodeList(districtName: "Hazaribagh",districtCode: "255"),
  const DistrictCodeList(districtName: "Jamtara",districtCode: "259"),
  const DistrictCodeList(districtName: "Khunti",districtCode: "252"),
  const DistrictCodeList(districtName: "Koderma",districtCode: "241"),
  const DistrictCodeList(districtName: "Latehar",districtCode: "244"),
  const DistrictCodeList(districtName: "Lohardaga",districtCode: "250"),
  const DistrictCodeList(districtName: "Pakur",districtCode: "261"),
  const DistrictCodeList(districtName: "Palamu",districtCode: "246"),
  const DistrictCodeList(districtName: "Ramgarh",districtCode: "254"),
  const DistrictCodeList(districtName: "Ranchi",districtCode: "240"),
  const DistrictCodeList(districtName: "Sahibganj",districtCode: "260"),
  const DistrictCodeList(districtName: "Saraikela-Kharsawan",districtCode: "248"),
  const DistrictCodeList(districtName: "Simdega",districtCode: "249"),
  const DistrictCodeList(districtName: "West Singhbhum",districtCode: "263"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];

const List<DistrictCodeList> JKList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Anantnag",districtCode: "224"),
  const DistrictCodeList(districtName: "Bandipora",districtCode: "223"),
  const DistrictCodeList(districtName: "Baramulla",districtCode: "225"),
  const DistrictCodeList(districtName: "Budgam",districtCode: "229"),
  const DistrictCodeList(districtName: "Doda",districtCode: "232"),
  const DistrictCodeList(districtName: "Ganderbal",districtCode: "228"),
  const DistrictCodeList(districtName: "Jammu",districtCode: "230"),
  const DistrictCodeList(districtName: "Kathua",districtCode: "234"),
  const DistrictCodeList(districtName: "Kishtwar",districtCode: "231"),
  const DistrictCodeList(districtName: "Kulgam",districtCode: "221"),
  const DistrictCodeList(districtName: "Kupwara",districtCode: "226"),
  const DistrictCodeList(districtName: "Mirpur",districtCode: "-1"),
  const DistrictCodeList(districtName: "Muzaffarabad",districtCode: "-1"),
  const DistrictCodeList(districtName: "Pulwama",districtCode: "227"),
  const DistrictCodeList(districtName: "Punch",districtCode: "238"),
  const DistrictCodeList(districtName: "Rajouri",districtCode: "237"),
  const DistrictCodeList(districtName: "Ramban",districtCode: "235"),
  const DistrictCodeList(districtName: "Reasi",districtCode: "239"),
  const DistrictCodeList(districtName: "Samba",districtCode: "236"),
  const DistrictCodeList(districtName: "Shopiyan",districtCode: "222"),
  const DistrictCodeList(districtName: "Srinagar",districtCode: "220"),
  const DistrictCodeList(districtName: "Udhampur",districtCode: "233"),
];

const List<DistrictCodeList> KAList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Bagalkote",districtCode: "270"),
  const DistrictCodeList(districtName: "Ballari",districtCode: "274"),
  const DistrictCodeList(districtName: "Belagavi",districtCode: "-1"),
  const DistrictCodeList(districtName: "Bengaluru Rural",districtCode: "276"),
  const DistrictCodeList(districtName: "Bengaluru Urban",districtCode: "265"),
  const DistrictCodeList(districtName: "Bidar",districtCode: "272"),
  const DistrictCodeList(districtName: "Chamarajanagara",districtCode: "271"),
  const DistrictCodeList(districtName: "Chikkaballapura",districtCode: "291"),
  const DistrictCodeList(districtName: "Chikkamagaluru",districtCode: "273"),
  const DistrictCodeList(districtName: "Chitradurga",districtCode: "268"),
  const DistrictCodeList(districtName: "Dakshina Kannada",districtCode: "269"),
  const DistrictCodeList(districtName: "Davanagere",districtCode: "275"),
  const DistrictCodeList(districtName: "Dharwad",districtCode: "278"),
  const DistrictCodeList(districtName: "Gadag",districtCode: "280"),
  const DistrictCodeList(districtName: "Hassan",districtCode: "289"),
  const DistrictCodeList(districtName: "Haveri",districtCode: "279"),
  const DistrictCodeList(districtName: "Kalaburagi",districtCode: "-1"),
  const DistrictCodeList(districtName: "Kodagu",districtCode: "283"),
  const DistrictCodeList(districtName: "Kolar",districtCode: "277"),
  const DistrictCodeList(districtName: "Koppal",districtCode: "282"),
  const DistrictCodeList(districtName: "Mandya",districtCode: "290"),
  const DistrictCodeList(districtName: "Mysuru",districtCode: "266"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Raichur",districtCode: "284"),
  const DistrictCodeList(districtName: "Ramanagara",districtCode: "292"),
  const DistrictCodeList(districtName: "Shivamogga",districtCode: "287"),
  const DistrictCodeList(districtName: "Tumakuru",districtCode: "288"),
  const DistrictCodeList(districtName: "Udupi",districtCode: "286"),
  const DistrictCodeList(districtName: "Uttara Kannada",districtCode: "281"),
  const DistrictCodeList(districtName: "Vijayapura",districtCode: "293"),
  const DistrictCodeList(districtName: "Yadgir",districtCode: "285"),
];

const List<DistrictCodeList> KLList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Alappuzha",districtCode: "301"),
  const DistrictCodeList(districtName: "Ernakulam",districtCode: "307"),
  const DistrictCodeList(districtName: "Idukki",districtCode: "306"),
  const DistrictCodeList(districtName: "Kannur",districtCode: "297"),
  const DistrictCodeList(districtName: "Kasaragod",districtCode: "295"),
  const DistrictCodeList(districtName: "Kollam",districtCode: "298"),
  const DistrictCodeList(districtName: "Kottayam",districtCode: "304"),
  const DistrictCodeList(districtName: "Kozhikode",districtCode: "305"),
  const DistrictCodeList(districtName: "Malappuram",districtCode: "302"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Palakkad",districtCode: "308"),
  const DistrictCodeList(districtName: "Pathanamthitta",districtCode: "300"),
  const DistrictCodeList(districtName: "Thiruvananthapuram",districtCode: "296"),
  const DistrictCodeList(districtName: "Thrissur",districtCode: "303"),
  const DistrictCodeList(districtName: "Wayanad",districtCode: "299"),
];

const List<DistrictCodeList> LAList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Kargil",districtCode: "309"),
  const DistrictCodeList(districtName: "Leh",districtCode: "310"),
];

const List<DistrictCodeList> LDList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Lakshadweep",districtCode: "311"),
];

const List<DistrictCodeList> MHList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Ahmednagar",districtCode: "391"),
  const DistrictCodeList(districtName: "Akola",districtCode: "364"),
  const DistrictCodeList(districtName: "Amravati",districtCode: "366"),
  const DistrictCodeList(districtName: "Aurangabad",districtCode: "397"),
  const DistrictCodeList(districtName: "Beed",districtCode: "384"),
  const DistrictCodeList(districtName: "Bhandara",districtCode: "370"),
  const DistrictCodeList(districtName: "Buldhana",districtCode: "367"),
  const DistrictCodeList(districtName: "Chandrapur",districtCode: "380"),
  const DistrictCodeList(districtName: "Dhule",districtCode: "388"),
  const DistrictCodeList(districtName: "Gadchiroli",districtCode: "379"),
  const DistrictCodeList(districtName: "Gondia",districtCode: "378"),
  const DistrictCodeList(districtName: "Hingoli",districtCode: "386"),
  const DistrictCodeList(districtName: "Jalgaon",districtCode: "390"),
  const DistrictCodeList(districtName: "Jalna",districtCode: "396"),
  const DistrictCodeList(districtName: "Kolhapur",districtCode: "371"),
  const DistrictCodeList(districtName: "Latur",districtCode: "383"),
  const DistrictCodeList(districtName: "Mumbai",districtCode: "395"),
  const DistrictCodeList(districtName: "Mumbai Suburban",districtCode: "-1"),
  const DistrictCodeList(districtName: "Nagpur",districtCode: "365"),
  const DistrictCodeList(districtName: "Nanded",districtCode: "382"),
  const DistrictCodeList(districtName: "Nandurbar",districtCode: "387"),
  const DistrictCodeList(districtName: "Nashik",districtCode: "389"),
  const DistrictCodeList(districtName: "Osmanabad",districtCode: "381"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Palghar",districtCode: "394"),
  const DistrictCodeList(districtName: "Parbhani",districtCode: "385"),
  const DistrictCodeList(districtName: "Pune",districtCode: "363"),
  const DistrictCodeList(districtName: "Raigad",districtCode: "393"),
  const DistrictCodeList(districtName: "Ratnagiri",districtCode: "372"),
  const DistrictCodeList(districtName: "Sangli",districtCode: "373"),
  const DistrictCodeList(districtName: "Satara",districtCode: "376"),
  const DistrictCodeList(districtName: "Sindhudurg",districtCode: "374"),
  const DistrictCodeList(districtName: "Solapur",districtCode: "375"),
  const DistrictCodeList(districtName: "Thane",districtCode: "392"),
  const DistrictCodeList(districtName: "Wardha",districtCode: "377"),
  const DistrictCodeList(districtName: "Washim",districtCode: "369"),
  const DistrictCodeList(districtName: "Yavatmal",districtCode: "368"),

];
const List<DistrictCodeList> MLList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "East Garo Hills",districtCode: "424"),
  const DistrictCodeList(districtName: "East Jaintia Hills",districtCode: "418"),
  const DistrictCodeList(districtName: "East Khasi Hills",districtCode: "414"),
  const DistrictCodeList(districtName: "North Garo Hills",districtCode: "423"),
  const DistrictCodeList(districtName: "Ribhoi",districtCode: "417"),
  const DistrictCodeList(districtName: "South Garo Hills",districtCode: "421"),
  const DistrictCodeList(districtName: "South West Garo Hills",districtCode: "422"),
  const DistrictCodeList(districtName: "South West Khasi Hills",districtCode: "415"),
  const DistrictCodeList(districtName: "West Garo Hills",districtCode: "420"),
  const DistrictCodeList(districtName: "West Jaintia Hills",districtCode: "416"),
  const DistrictCodeList(districtName: "West Khasi Hills",districtCode: "419"),
];
const List<DistrictCodeList> MNList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "CAPF Personnel",districtCode: "-1"),
  const DistrictCodeList(districtName: "Bishnupur",districtCode: "398"),
  const DistrictCodeList(districtName: "Chandel",districtCode: "399"),
  const DistrictCodeList(districtName: "Churachandpur",districtCode: "400"),
  const DistrictCodeList(districtName: "Imphal East",districtCode: "401"),
  const DistrictCodeList(districtName: "Imphal West",districtCode: "402"),
  const DistrictCodeList(districtName: "Jiribam",districtCode: "410"),
  const DistrictCodeList(districtName: "Kakching",districtCode: "413"),
  const DistrictCodeList(districtName: "Kamjong",districtCode: "409"),
  const DistrictCodeList(districtName: "Kangpokpi",districtCode: "408"),
  const DistrictCodeList(districtName: "Noney",districtCode: "412"),
  const DistrictCodeList(districtName: "Pherzawl",districtCode: "411"),
  const DistrictCodeList(districtName: "Senapati",districtCode: "403"),
  const DistrictCodeList(districtName: "Tamenglong",districtCode: "401"),
  const DistrictCodeList(districtName: "Tengnoupal",districtCode: "407"),
  const DistrictCodeList(districtName: "Thoubal",districtCode: "405"),
  const DistrictCodeList(districtName: "Ukhrul",districtCode: "406"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),

];
const List<DistrictCodeList> MPList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Agar Malwa",districtCode: "320"),
  const DistrictCodeList(districtName: "Alirajpur",districtCode: "357"),
  const DistrictCodeList(districtName: "Anuppur",districtCode: "334"),
  const DistrictCodeList(districtName: "Ashoknagar",districtCode: "354"),
  const DistrictCodeList(districtName: "Balaghat",districtCode: "338"),
  const DistrictCodeList(districtName: "Barwani",districtCode: "343"),
  const DistrictCodeList(districtName: "Betul",districtCode: "362"),
  const DistrictCodeList(districtName: "Bhind",districtCode: "351"),
  const DistrictCodeList(districtName: "Bhopal",districtCode: "312"),
  const DistrictCodeList(districtName: "Burhanpur",districtCode: "342"),
  const DistrictCodeList(districtName: "Chhatarpur",districtCode: "328"),
  const DistrictCodeList(districtName: "Chhindwara",districtCode: "337"),
  const DistrictCodeList(districtName: "Damoh",districtCode: "327"),
  const DistrictCodeList(districtName: "Datia",districtCode: "350"),
  const DistrictCodeList(districtName: "Dewas",districtCode: "324"),
  const DistrictCodeList(districtName: "Dhar",districtCode: "341"),
  const DistrictCodeList(districtName: "Dindori",districtCode: "336"),
  const DistrictCodeList(districtName: "Guna",districtCode: "348"),
  const DistrictCodeList(districtName: "Gwalior",districtCode: "313"),
  const DistrictCodeList(districtName: "Harda",districtCode: "361"),
  const DistrictCodeList(districtName: "Hoshangabad",districtCode: "360"),
  const DistrictCodeList(districtName: "Indore",districtCode: "314"),
  const DistrictCodeList(districtName: "Jabalpur",districtCode: "315"),
  const DistrictCodeList(districtName: "Jhabua",districtCode: "340"),
  const DistrictCodeList(districtName: "Katni",districtCode: "353"),
  const DistrictCodeList(districtName: "Khandwa",districtCode: "339"),
  const DistrictCodeList(districtName: "Khargone",districtCode: "344"),
  const DistrictCodeList(districtName: "Mandla",districtCode: "335"),
  const DistrictCodeList(districtName: "Mandsaur",districtCode: "319"),
  const DistrictCodeList(districtName: "Morena",districtCode: "347"),
  const DistrictCodeList(districtName: "Narsinghpur",districtCode: "352"),
  const DistrictCodeList(districtName: "Neemuch",districtCode: "323"),
  const DistrictCodeList(districtName: "Niwari",districtCode: "-1"),
  const DistrictCodeList(districtName: "Other Region",districtCode: "-1"),
  const DistrictCodeList(districtName: "Panna",districtCode: "326"),
  const DistrictCodeList(districtName: "Raisen",districtCode: "359"),
  const DistrictCodeList(districtName: "Rajgarh",districtCode: "358"),
  const DistrictCodeList(districtName: "Ratlam",districtCode: "322"),
  const DistrictCodeList(districtName: "Rewa",districtCode: "316"),
  const DistrictCodeList(districtName: "Sagar",districtCode: "317"),
  const DistrictCodeList(districtName: "Satna",districtCode: "333"),
  const DistrictCodeList(districtName: "Sehore",districtCode: "356"),
  const DistrictCodeList(districtName: "Seoni",districtCode: "349"),
  const DistrictCodeList(districtName: "Shahdol",districtCode: "332"),
  const DistrictCodeList(districtName: "Shajapur",districtCode: "321"),
  const DistrictCodeList(districtName: "Sheopur",districtCode: "346"),
  const DistrictCodeList(districtName: "Shivpuri",districtCode: "345"),
  const DistrictCodeList(districtName: "Sidhi",districtCode: "331"),
  const DistrictCodeList(districtName: "Singrauli",districtCode: "330"),
  const DistrictCodeList(districtName: "Tikamgarh",districtCode: "325"),
  const DistrictCodeList(districtName: "Ujjain",districtCode: "318"),
  const DistrictCodeList(districtName: "Umaria",districtCode: "329"),
  const DistrictCodeList(districtName: "Vidisha",districtCode: "355"),


];
const List<DistrictCodeList> MZList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Aizawl",districtCode: "425"),
  const DistrictCodeList(districtName: "Champhai",districtCode: "429"),
  const DistrictCodeList(districtName: "Hnahthial",districtCode: "-1"),
  const DistrictCodeList(districtName: "Khawzawl",districtCode: "-1"),
  const DistrictCodeList(districtName: "Kolasib",districtCode: "428"),
  const DistrictCodeList(districtName: "Lawngtlai",districtCode: "432"),
  const DistrictCodeList(districtName: "Lunglei",districtCode: "431"),
  const DistrictCodeList(districtName: "Mamit",districtCode: "427"),
  const DistrictCodeList(districtName: "Saiha",districtCode: "433"),
  const DistrictCodeList(districtName: "Saitual",districtCode: "-1"),
  const DistrictCodeList(districtName: "Serchhip",districtCode: "430"),
];
const List<DistrictCodeList> NLList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Others",districtCode: "-1"),
  const DistrictCodeList(districtName: "Dimapur",districtCode: "434"),
  const DistrictCodeList(districtName: "Kiphire",districtCode: "444"),
  const DistrictCodeList(districtName: "Kohima",districtCode: "441"),
  const DistrictCodeList(districtName: "Longleng",districtCode: "438"),
  const DistrictCodeList(districtName: "Mokokchung",districtCode: "437"),
  const DistrictCodeList(districtName: "Mon",districtCode: "439"),
  const DistrictCodeList(districtName: "Peren",districtCode: "435"),
  const DistrictCodeList(districtName: "Phek",districtCode: "443"),
  const DistrictCodeList(districtName: "Tuensang",districtCode: "440"),
  const DistrictCodeList(districtName: "Wokha",districtCode: "436"),
  const DistrictCodeList(districtName: "Zunheboto",districtCode: "442"),


];
const List<DistrictCodeList> ORList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "State Pool",districtCode: "-1"),
  const DistrictCodeList(districtName: "Others",districtCode: "-1"),
  const DistrictCodeList(districtName: "Angul",districtCode: "445"),
  const DistrictCodeList(districtName: "Balangir",districtCode: "448"),
  const DistrictCodeList(districtName: "Balasore",districtCode: "447"),
  const DistrictCodeList(districtName: "Bargarh",districtCode: "472"),
  const DistrictCodeList(districtName: "Bhadrak",districtCode: "454"),
  const DistrictCodeList(districtName: "Boudh",districtCode: "468"),
  const DistrictCodeList(districtName: "Cuttack",districtCode: "457"),
  const DistrictCodeList(districtName: "Deogarh",districtCode: "473"),
  const DistrictCodeList(districtName: "Dhenkanal",districtCode: "458"),
  const DistrictCodeList(districtName: "Gajapati",districtCode: "467"),
  const DistrictCodeList(districtName: "Ganjam",districtCode: "449"),
  const DistrictCodeList(districtName: "Jagatsinghpur",districtCode: "459"),
  const DistrictCodeList(districtName: "Jajpur",districtCode: "460"),
  const DistrictCodeList(districtName: "Jharsuguda",districtCode: "474"),
  const DistrictCodeList(districtName: "Kalahandi",districtCode: "464"),
  const DistrictCodeList(districtName: "Kandhamal",districtCode: "450"),
  const DistrictCodeList(districtName: "Kendrapara",districtCode: "461"),
  const DistrictCodeList(districtName: "Kendujhar",districtCode: "455"),
  const DistrictCodeList(districtName: "Khordha",districtCode: "446"),
  const DistrictCodeList(districtName: "Koraput",districtCode: "451"),
  const DistrictCodeList(districtName: "Malkangiri",districtCode: "469"),
  const DistrictCodeList(districtName: "Mayurbhanj",districtCode: "456"),
  const DistrictCodeList(districtName: "Nabarangapur",districtCode: "470"),
  const DistrictCodeList(districtName: "Nayagarh",districtCode: "462"),
  const DistrictCodeList(districtName: "Nuapada",districtCode: "465"),
  const DistrictCodeList(districtName: "Puri",districtCode: "463"),
  const DistrictCodeList(districtName: "Rayagada",districtCode: "471"),
  const DistrictCodeList(districtName: "Sambalpur",districtCode: "452"),
  const DistrictCodeList(districtName: "Subarnapur",districtCode: "466"),
  const DistrictCodeList(districtName: "Sundargarh",districtCode: "453"),
];

const List<DistrictCodeList> PBList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Amritsar",districtCode: "485"),
  const DistrictCodeList(districtName: "Barnala",districtCode: "483"),
  const DistrictCodeList(districtName: "Bathinda",districtCode: "493"),
  const DistrictCodeList(districtName: "Faridkot",districtCode: "499"),
  const DistrictCodeList(districtName: "Fatehgarh Sahib",districtCode: "484"),
  const DistrictCodeList(districtName: "Fazilka",districtCode: "487"),
  const DistrictCodeList(districtName: "Ferozepur",districtCode: "480"),
  const DistrictCodeList(districtName: "Gurdaspur",districtCode: "489"),
  const DistrictCodeList(districtName: "Hoshiarpur",districtCode: "481"),
  const DistrictCodeList(districtName: "Jalandhar",districtCode: "492"),
  const DistrictCodeList(districtName: "Kapurthala",districtCode: "479"),
  const DistrictCodeList(districtName: "Ludhiana",districtCode: "488"),
  const DistrictCodeList(districtName: "Mansa",districtCode: "482"),
  const DistrictCodeList(districtName: "Moga",districtCode: "491"),
  const DistrictCodeList(districtName: "Pathankot",districtCode: "486"),
  const DistrictCodeList(districtName: "Patiala",districtCode: "494"),
  const DistrictCodeList(districtName: "Rupnagar",districtCode: "497"),
  const DistrictCodeList(districtName: "S.A.S. Nagar",districtCode: "496"),
  const DistrictCodeList(districtName: "Sangrur",districtCode: "498"),
  const DistrictCodeList(districtName: "Shahid Bhagat Singh Nagar",districtCode: "500"),
  const DistrictCodeList(districtName: "Sri Muktsar Sahib",districtCode: "490"),
  const DistrictCodeList(districtName: "Tarn Taran",districtCode: "495"),
];

const List<DistrictCodeList> PYList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Karaikal",districtCode: "476"),
  const DistrictCodeList(districtName: "Mahe",districtCode: "477"),
  const DistrictCodeList(districtName: "Puducherry",districtCode: "475"),
  const DistrictCodeList(districtName: "Yanam",districtCode: "478"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];

const List<DistrictCodeList> RJList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Ajmer",districtCode: "507"),
  const DistrictCodeList(districtName: "Alwar",districtCode: "512"),
  const DistrictCodeList(districtName: "Banswara",districtCode: "519"),
  const DistrictCodeList(districtName: "Baran",districtCode: "516"),
  const DistrictCodeList(districtName: "Barmer",districtCode: "528"),
  const DistrictCodeList(districtName: "Bharatpur",districtCode: "508"),
  const DistrictCodeList(districtName: "Bhilwara",districtCode: "523"),
  const DistrictCodeList(districtName: "Bikaner",districtCode: "501"),
  const DistrictCodeList(districtName: "BSF Camp",districtCode: "-1"),
  const DistrictCodeList(districtName: "Bundi",districtCode: "514"),
  const DistrictCodeList(districtName: "Chittorgarh",districtCode: "521"),
  const DistrictCodeList(districtName: "Churu",districtCode: "530"),
  const DistrictCodeList(districtName: "Dausa",districtCode: "511"),
  const DistrictCodeList(districtName: "Dholpur",districtCode: "524"),
  const DistrictCodeList(districtName: "Dungarpur",districtCode: "520"),
  const DistrictCodeList(districtName: "Evacuees",districtCode: "-1"),
  const DistrictCodeList(districtName: "Ganganagar",districtCode: "-1"),
  const DistrictCodeList(districtName: "Hanumangarh",districtCode: "517"),
  const DistrictCodeList(districtName: "Italians",districtCode: "-1"),
  const DistrictCodeList(districtName: "Jaipur",districtCode: "505"),
  const DistrictCodeList(districtName: "Jaisalmer",districtCode: "527"),
  const DistrictCodeList(districtName: "Jalore",districtCode: "533"),
  const DistrictCodeList(districtName: "Jhalawar",districtCode: "515"),
  const DistrictCodeList(districtName: "Jhunjhunu",districtCode: "510"),
  const DistrictCodeList(districtName: "Jodhpur",districtCode: "502"),
  const DistrictCodeList(districtName: "Karauli",districtCode: "525"),
  const DistrictCodeList(districtName: "Kota",districtCode: "503"),
  const DistrictCodeList(districtName: "Nagaur",districtCode: "532"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Pali",districtCode: "529"),
  const DistrictCodeList(districtName: "Pratapgarh",districtCode: "522"),
  const DistrictCodeList(districtName: "Rajsamand",districtCode: "518"),
  const DistrictCodeList(districtName: "Sawai Madhopur",districtCode: "534"),
  const DistrictCodeList(districtName: "Sikar",districtCode: "513"),
  const DistrictCodeList(districtName: "Sirohi",districtCode: "531"),
  const DistrictCodeList(districtName: "Tonk",districtCode: "526"),
  const DistrictCodeList(districtName: "Udaipur",districtCode: "504"),

];

const List<DistrictCodeList> SKList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "East Sikkim",districtCode: "535"),
  const DistrictCodeList(districtName: "North Sikkim",districtCode: "537"),
  const DistrictCodeList(districtName: "South Sikkim",districtCode: "538"),
  const DistrictCodeList(districtName: "West Sikkim",districtCode: "536"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];

const List<DistrictCodeList> TGList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Foreign Evacuees",districtCode: "-1"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Adilabad",districtCode: "582"),
  const DistrictCodeList(districtName: "Bhadradri Kothagudem",districtCode: "583"),
  const DistrictCodeList(districtName: "Hyderabad",districtCode: "581"),
  const DistrictCodeList(districtName: "Jagtial",districtCode: "584"),
  const DistrictCodeList(districtName: "Jangaon",districtCode: "585"),
  const DistrictCodeList(districtName: "Jayashankar Bhupalapally",districtCode: "586"),
  const DistrictCodeList(districtName: "Jogulamba Gadwal",districtCode: "587"),
  const DistrictCodeList(districtName: "Kamareddy",districtCode: "588"),
  const DistrictCodeList(districtName: "Karimnagar",districtCode: "589"),
  const DistrictCodeList(districtName: "Khammam",districtCode: "590"),
  const DistrictCodeList(districtName: "Komaram Bheem",districtCode: "591"),
  const DistrictCodeList(districtName: "Mahabubabad",districtCode: "592"),
  const DistrictCodeList(districtName: "Mahabubnagar",districtCode: "593"),
  const DistrictCodeList(districtName: "Mancherial",districtCode: "594"),
  const DistrictCodeList(districtName: "Medak",districtCode: "595"),
  const DistrictCodeList(districtName: "Medchal Malkajgiri",districtCode: "596"),
  const DistrictCodeList(districtName: "Mulugu",districtCode: "612"),
  const DistrictCodeList(districtName: "Nagarkurnool",districtCode: "597"),
  const DistrictCodeList(districtName: "Nalgonda",districtCode: "598"),
  const DistrictCodeList(districtName: "Narayanpet",districtCode: "613"),
  const DistrictCodeList(districtName: "Nirmal",districtCode: "599"),
  const DistrictCodeList(districtName: "Nizamabad",districtCode: "600"),
  const DistrictCodeList(districtName: "Peddapalli",districtCode: "601"),
  const DistrictCodeList(districtName: "Rajanna Sircilla",districtCode: "602"),
  const DistrictCodeList(districtName: "Ranga Reddy",districtCode: "603"),
  const DistrictCodeList(districtName: "Sangareddy",districtCode: "604"),
  const DistrictCodeList(districtName: "Siddipet",districtCode: "605"),
  const DistrictCodeList(districtName: "Suryapet",districtCode: "606"),
  const DistrictCodeList(districtName: "Vikarabad",districtCode: "607"),
  const DistrictCodeList(districtName: "Wanaparthy",districtCode: "608"),
  const DistrictCodeList(districtName: "Warangal Rural",districtCode: "609"),
  const DistrictCodeList(districtName: "Warangal Urban",districtCode: "610"),
  const DistrictCodeList(districtName: "Yadadri Bhuvanagiri",districtCode: "611"),
  const DistrictCodeList(districtName: "Unknown",districtCode: "-1"),
];

const List<DistrictCodeList> TNList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Railway Quarantine",districtCode: "-1"),
  const DistrictCodeList(districtName: "Airport Quarantine",districtCode: "-1"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Ariyalur",districtCode: "779"),
  const DistrictCodeList(districtName: "Chengalpattu",districtCode: "565"),
  const DistrictCodeList(districtName: "Chennai",districtCode: "571"),
  const DistrictCodeList(districtName: "Coimbatore",districtCode: "539"),
  const DistrictCodeList(districtName: "Cuddalore",districtCode: "547"),
  const DistrictCodeList(districtName: "Dharmapuri",districtCode: "566"),
  const DistrictCodeList(districtName: "Dindigul",districtCode: "556"),
  const DistrictCodeList(districtName: "Erode",districtCode: "563"),
  const DistrictCodeList(districtName: "Kallakurichi",districtCode: "552"),
  const DistrictCodeList(districtName: "Kancheepuram",districtCode: "557"),
  const DistrictCodeList(districtName: "Kanyakumari",districtCode: "544"),
  const DistrictCodeList(districtName: "Karur",districtCode: "559"),
  const DistrictCodeList(districtName: "Krishnagiri",districtCode: "562"),
  const DistrictCodeList(districtName: "Madurai",districtCode: "540"),
  const DistrictCodeList(districtName: "Nagapattinam",districtCode: "576"),
  const DistrictCodeList(districtName: "Namakkal",districtCode: "558"),
  const DistrictCodeList(districtName: "Nilgiris",districtCode: "577"),
  const DistrictCodeList(districtName: "Perambalur",districtCode: "570"),
  const DistrictCodeList(districtName: "Pudukkottai",districtCode: "546"),
  const DistrictCodeList(districtName: "Ramanathapuram",districtCode: "567"),
  const DistrictCodeList(districtName: "Ranipet",districtCode: "781"),
  const DistrictCodeList(districtName: "Salem",districtCode: "545"),
  const DistrictCodeList(districtName: "Sivaganga",districtCode: "561"),
  const DistrictCodeList(districtName: "Tenkasi",districtCode: "551"),
  const DistrictCodeList(districtName: "Thanjavur",districtCode: "541"),
  const DistrictCodeList(districtName: "Theni",districtCode: "569"),
  const DistrictCodeList(districtName: "Thiruvallur",districtCode: "572"),
  const DistrictCodeList(districtName: "Thiruvarur",districtCode: "574"),
  const DistrictCodeList(districtName: "Thoothukkudi",districtCode: "554"),
  const DistrictCodeList(districtName: "Tiruchirappalli",districtCode: "560"),
  const DistrictCodeList(districtName: "Tirunelveli",districtCode: "548"),
  const DistrictCodeList(districtName: "Tirupathur",districtCode: "550"),
  const DistrictCodeList(districtName: "Tiruppur",districtCode: "568"),
  const DistrictCodeList(districtName: "Tiruvannamalai",districtCode: "553"),
  const DistrictCodeList(districtName: "Vellore",districtCode: "543"),
  const DistrictCodeList(districtName: "Viluppuram",districtCode: "542"),
  const DistrictCodeList(districtName: "Virudhunagar",districtCode: "549"),
];
const List<DistrictCodeList> TRList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Dhalai",districtCode: "614"),
  const DistrictCodeList(districtName: "Gomati",districtCode: "615"),
  const DistrictCodeList(districtName: "Khowai",districtCode: "616"),
  const DistrictCodeList(districtName: "North Tripura",districtCode: "617"),
  const DistrictCodeList(districtName: "Sipahijala",districtCode: "618"),
  const DistrictCodeList(districtName: "South Tripura",districtCode: "619"),
  const DistrictCodeList(districtName: "Unokoti",districtCode: "620"),
  const DistrictCodeList(districtName: "West Tripura",districtCode: "621"),
];

const List<DistrictCodeList> UPList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Agra",districtCode: "622"),
  const DistrictCodeList(districtName: "Aligarh",districtCode: "623"),
  const DistrictCodeList(districtName: "Ambedkar Nagar",districtCode: "625"),
  const DistrictCodeList(districtName: "Amethi",districtCode: "626"),
  const DistrictCodeList(districtName: "Amroha",districtCode: "627"),
  const DistrictCodeList(districtName: "Auraiya",districtCode: "628"),
  const DistrictCodeList(districtName: "Ayodhya",districtCode: "646"),
  const DistrictCodeList(districtName: "Azamgarh",districtCode: "629"),
  const DistrictCodeList(districtName: "Baghpat",districtCode: "631"),
  const DistrictCodeList(districtName: "Bahraich",districtCode: "632"),
  const DistrictCodeList(districtName: "Ballia",districtCode: "634"),
  const DistrictCodeList(districtName: "Balrampur",districtCode: "633"),
  const DistrictCodeList(districtName: "Banda",districtCode: "635"),
  const DistrictCodeList(districtName: "Barabanki",districtCode: "636"),
  const DistrictCodeList(districtName: "Bareilly",districtCode: "637"),
  const DistrictCodeList(districtName: "Basti",districtCode: "638"),
  const DistrictCodeList(districtName: "Bhadohi",districtCode: "687"),
  const DistrictCodeList(districtName: "Bijnor",districtCode: "639"),
  const DistrictCodeList(districtName: "Budaun",districtCode: "630"),
  const DistrictCodeList(districtName: "Bulandshahr",districtCode: "640"),
  const DistrictCodeList(districtName: "Chandauli",districtCode: "641"),
  const DistrictCodeList(districtName: "Chitrakoot",districtCode: "642"),
  const DistrictCodeList(districtName: "Deoria",districtCode: "643"),
  const DistrictCodeList(districtName: "Etah",districtCode: "644"),
  const DistrictCodeList(districtName: "Etawah",districtCode: "645"),
  const DistrictCodeList(districtName: "Farrukhabad",districtCode: "647"),
  const DistrictCodeList(districtName: "Fatehpur",districtCode: "548"),
  const DistrictCodeList(districtName: "Firozabad",districtCode: "649"),
  const DistrictCodeList(districtName: "Gautam Buddha Nagar",districtCode: "650"),
  const DistrictCodeList(districtName: "Ghaziabad",districtCode: "651"),
  const DistrictCodeList(districtName: "Ghazipur",districtCode: "652"),
  const DistrictCodeList(districtName: "Gonda",districtCode: "653"),
  const DistrictCodeList(districtName: "Gorakhpur",districtCode: "654"),
  const DistrictCodeList(districtName: "Hamirpur",districtCode: "655"),
  const DistrictCodeList(districtName: "Hapur",districtCode: "656"),
  const DistrictCodeList(districtName: "Hardoi",districtCode: "657"),
  const DistrictCodeList(districtName: "Hathras",districtCode: "658"),
  const DistrictCodeList(districtName: "Jalaun",districtCode: "659"),
  const DistrictCodeList(districtName: "Jaunpur",districtCode: "660"),
  const DistrictCodeList(districtName: "Jhansi",districtCode: "661"),
  const DistrictCodeList(districtName: "Kannauj",districtCode: "662"),
  const DistrictCodeList(districtName: "Kanpur Dehat",districtCode: "663"),
  const DistrictCodeList(districtName: "Kanpur Nagar",districtCode: "664"),
  const DistrictCodeList(districtName: "Kasganj",districtCode: "665"),
  const DistrictCodeList(districtName: "Kaushambi",districtCode: "666"),
  const DistrictCodeList(districtName: "Kushinagar",districtCode: "667"),
  const DistrictCodeList(districtName: "Lakhimpur Kheri",districtCode: "668"),
  const DistrictCodeList(districtName: "Lalitpur",districtCode: "669"),
  const DistrictCodeList(districtName: "Lucknow",districtCode: "670"),
  const DistrictCodeList(districtName: "Maharajganj",districtCode: "671"),
  const DistrictCodeList(districtName: "Mahoba",districtCode: "672"),
  const DistrictCodeList(districtName: "Mainpuri",districtCode: "673"),
  const DistrictCodeList(districtName: "Mathura",districtCode: "674"),
  const DistrictCodeList(districtName: "Mau",districtCode: "675"),
  const DistrictCodeList(districtName: "Meerut",districtCode: "676"),
  const DistrictCodeList(districtName: "Mirzapur",districtCode: "677"),
  const DistrictCodeList(districtName: "Moradabad",districtCode: "678"),
  const DistrictCodeList(districtName: "Muzaffarnagar",districtCode: "679"),
  const DistrictCodeList(districtName: "Pilibhit",districtCode: "680"),
  const DistrictCodeList(districtName: "Pratapgarh",districtCode: "682"),
  const DistrictCodeList(districtName: "Prayagraj",districtCode: "624"),
  const DistrictCodeList(districtName: "Rae Bareli",districtCode: "681"),
  const DistrictCodeList(districtName: "Rampur",districtCode: "683"),
  const DistrictCodeList(districtName: "Saharanpur",districtCode: "684"),
  const DistrictCodeList(districtName: "Sambhal",districtCode: "685"),
  const DistrictCodeList(districtName: "Sant Kabir Nagar",districtCode: "686"),
  const DistrictCodeList(districtName: "Shahjahanpur",districtCode: "688"),
  const DistrictCodeList(districtName: "Shamli",districtCode: "689"),
  const DistrictCodeList(districtName: "Shrawasti",districtCode: "690"),
  const DistrictCodeList(districtName: "Siddharthnagar",districtCode: "691"),
  const DistrictCodeList(districtName: "Sitapur",districtCode: "692"),
  const DistrictCodeList(districtName: "Sonbhadra",districtCode: "693"),
  const DistrictCodeList(districtName: "Unnao",districtCode: "695"),
  const DistrictCodeList(districtName: "Varanasi",districtCode: "696"),


];

const List<DistrictCodeList> UTList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Almora",districtCode: "704"),
  const DistrictCodeList(districtName: "Bageshwar",districtCode: "707"),
  const DistrictCodeList(districtName: "Chamoli",districtCode: "699"),
  const DistrictCodeList(districtName: "Champawat",districtCode: "708"),
  const DistrictCodeList(districtName: "Dehradun",districtCode: "697"),
  const DistrictCodeList(districtName: "Haridwar",districtCode: "702"),
  const DistrictCodeList(districtName: "Nainital",districtCode: "709"),
  const DistrictCodeList(districtName: "Pauri Garhwal",districtCode: "698"),
  const DistrictCodeList(districtName: "Pithoragarh",districtCode: "706"),
  const DistrictCodeList(districtName: "Rudraprayag",districtCode: "700"),
  const DistrictCodeList(districtName: "Tehri Garhwal",districtCode: "701"),
  const DistrictCodeList(districtName: "Udham Singh Nagar",districtCode: "705"),
  const DistrictCodeList(districtName: "Uttarkashi",districtCode: "703"),

];

const List<DistrictCodeList> WBList = const <DistrictCodeList>[
  const DistrictCodeList(districtName: "Alipurduar",districtCode: "710"),
  const DistrictCodeList(districtName: "Bankura",districtCode: "711"),
  const DistrictCodeList(districtName: "Birbhum",districtCode: "713"),
  const DistrictCodeList(districtName: "Cooch Behar",districtCode: "715"),
  const DistrictCodeList(districtName: "Dakshin Dinajpur",districtCode: "716"),
  const DistrictCodeList(districtName: "Darjeeling",districtCode: "717"),
  const DistrictCodeList(districtName: "Hooghly",districtCode: "720"),
  const DistrictCodeList(districtName: "Howrah",districtCode: "721"),
  const DistrictCodeList(districtName: "Jalpaiguri",districtCode: "722"),
  const DistrictCodeList(districtName: "Jhargram",districtCode: "723"),
  const DistrictCodeList(districtName: "Kalimpong",districtCode: "724"),
  const DistrictCodeList(districtName: "Kolkata",districtCode: "725"),
  const DistrictCodeList(districtName: "Malda",districtCode: "726"),
  const DistrictCodeList(districtName: "Murshidabad",districtCode: "727"),
  const DistrictCodeList(districtName: "Nadia",districtCode: "728"),
  const DistrictCodeList(districtName: "North 24 Parganas",districtCode: "730"),
  const DistrictCodeList(districtName: "Other State",districtCode: "-1"),
  const DistrictCodeList(districtName: "Paschim Bardhaman",districtCode: "737"),
  const DistrictCodeList(districtName: "Paschim Medinipur",districtCode: "731"),
  const DistrictCodeList(districtName: "Purba Bardhaman",districtCode: "-1"),
  const DistrictCodeList(districtName: "Purba Medinipur",districtCode: "732"),
  const DistrictCodeList(districtName: "Purulia",districtCode: "733"),
  const DistrictCodeList(districtName: "South 24 Parganas",districtCode: "735"),
  const DistrictCodeList(districtName: "Uttar Dinajpur",districtCode: "736"),
];
